CREATE IF NOT EXISTS DATABASE config_db;
CREATE IF NOT EXISTS DATABASE alerting_db;
CREATE IF NOT EXISTS DATABASE notifier_db;
CREATE IF NOT EXISTS DATABASE reports_db;

GRANT ALL PRIVILEGES ON DATABASE config_db TO alert;
GRANT ALL PRIVILEGES ON DATABASE alerting_db TO alert;
GRANT ALL PRIVILEGES ON DATABASE notifier_db TO alert;
GRANT ALL PRIVILEGES ON DATABASE reports_db TO alert;
